sudo: false

language: php
php:
  - 7.1

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache

before_install:
  # Install melody
  - curl -Lo $HOME/bin/melody http://get.sensiolabs.org/melody.phar
  - chmod +x $HOME/bin/melody

  # Retrieve documentation
  - bin/retrieve-documentation

  # Install dependencies
  - yarn install

script:
  # Check CS
  - yarn lint

  # Check build
  - yarn gatsby build
