sudo: required

language: php
php:
  - 7.1

before_install:

  # Install melody

  - sudo curl -Lo /usr/bin/melody http://get.sensiolabs.org/melody.phar
  - sudo chmod +x /usr/bin/melody

  # Retrieve documentation

  - bin/retrieve-documentation

  # Install dependencies

  - yarn install

script:

  # Check CS

  - yarn lint

  # Check build

  - yarn gatsby build
