version: "2"

services:
    web:
        image: node:6
        command: npm run dev
        working_dir: /app
        volumes:
            - ./:/app
            - node_modules:/app/node_modules
        ports:
            - "3000:3000"
            - "3030:3030"
            - "3001:3001"
            - "8080:8080"

    calavera:
        image: dunglas/calavera
        command: /in /out
        volumes:
            - ./data-src:/in
            - ./src/static/data:/out

volumes:
    node_modules:
        ~

